{% set name = "mcp-compose" %}

package:
  name: {{ name|lower }}
  version: "{{ VERSION }}"

source:
  path: .

channels:
  - conda-forge
  - datalayer

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python >=3.10
    - pip
    - hatchling >=1.21
  run:
    - python >=3.10
    - cryptography >=41.0.0
    - fastapi >=0.104.0
    - httpx >=0.25.0
    - importlib-metadata >=4.8.0
    - mcp >=1.2.1
    - prometheus_client
    - psutil >=5.9.0
    - pyjwt >=2.8.0
    - pydantic >=2
    - python-dotenv >=1.0.0
    - sse-starlette >=1.8.0
    - toml >=0.10.2
    - tomli >=2.0.0
    - typing-extensions >=4
    - uvicorn >=0.24.0

test:
  imports:
    - mcp_compose
  commands:
    - mcp-compose --help

about:
  home: https://github.com/datalayer/mcp-compose
  summary: 'Composition server for the Model Context Protocol (MCP).'
  description: |
    A powerful, production-ready framework for composing and orchestrating Model
    Context Protocol (MCP) servers with advanced management capabilities, REST API,
    and modern Web UI.  # Remember to specify the license variants for BSD, Apache,
    GPL, and LGPL.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://github.com/datalayer/mcp-compose
  dev_url: https://github.com/datalayer/mcp-compose

extra:
  recipe-maintainers:
    - datalayer
    - echarles
    - eleonorecharles
    - goanpeca

