{% set name = "mcp_compose" %}

package:
  name: {{ name|lower }}
  version: {{ environ.get("PKG_VERSION") }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: |
    python -m pip install --no-deps --no-build-isolation -vv .

requirements:
  host:
    - python >=3.10
    - pip
    - hatchling ~=1.21
  run:
    - python >=3.10
    - pyjwt >=2.8.0
    - cryptography >=41.0.0
    - fastapi >=0.104.0
    - httpx >=0.25.0
    - importlib-metadata >=4.8.0
    - psutil >=5.9.0
    - pydantic >=2
    - python-dotenv >=1.0.0
    - sse-starlette >=1.8.0
    - toml >=0.10.2
    - typing-extensions >=4
    - uvicorn >=0.24.0
    - tomli >=2.0.0
    - mcp[cli] >=1.2.1

test:
  requires:
    - pip
  commands:
    - python -c "import mcp_compose"
    - mcp-compose --help

about:
  home: https://github.com/datalayer/mcp-compose
  license: BSD-3-Clause
  license_file: LICENSE
  summary: "Composition server for the Model Context Protocol (MCP)."
  doc_url: https://github.com/datalayer/mcp-compose
  dev_url: https://github.com/datalayer/mcp-compose

extra:
  recipe-maintainers:
    - datalayer

